# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: |
          #!/bin/bash
                
          echo "Print working Directory"    
          pwd
          cd ./Server
          set +x
          cat <<EOT >> Dockerfile
          FROM node:lts-alpine
          WORKDIR /app
          COPY . .
          RUN npm i --save --legacy-peer-deps
          CMD [ "npm", "start" ]
          EXPOSE ${PORT}
          EOT"""
              }
          }
        displayName: Build Dockerfile      